version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly
  tests: true

linters:
  enable:
    - errcheck
    - staticcheck
    - unused
    - goconst
    - misspell
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - goconst

formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
