version: 2

project_name: tfjournal

force_token: github

before:
  hooks:
    - go mod tidy
    - make web

builds:
  - binary: tfjournal
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    formats:
      - binary

nfpms:
  - package_name: tfjournal
    formats:
      - apk
      - deb
      - rpm
      - archlinux
    maintainer: "pgagnidze <pgagnidze@pm.me>"
    vendor: "Owloops"
    homepage: "https://github.com/Owloops/tfjournal"
    license: "MIT"
    description: "Record Terraform runs with git context, timing, and resource events"
    section: "utils"
    priority: "optional"

brews:
  - name: tfjournal
    description: Record Terraform runs with git context, timing, and resource events
    homepage: https://github.com/Owloops/tfjournal
    license: MIT
    repository:
      owner: Owloops
      name: homebrew-tap
      token: "{{ .Env.GH_PAT }}"

checksum:
  name_template: checksums.txt

changelog:
  use: github
